-- chunkname: @scripts/settings/payload_speed_settings.lua

PayloadSpeedSettings = PayloadSpeedSettings or {}
PayloadSpeedSettings.flat = PayloadSpeedSettings.flat or {}
PayloadSpeedSettings.flat.most_friendlies = PayloadSpeedSettings.flat.most_friendlies or {}
PayloadSpeedSettings.flat.most_friendlies.speed = 1.15
PayloadSpeedSettings.flat.most_friendlies.acceleration = 0.5
PayloadSpeedSettings.flat.equal_amount = PayloadSpeedSettings.flat.equal_amount or {}
PayloadSpeedSettings.flat.equal_amount.speed = 0
PayloadSpeedSettings.flat.equal_amount.acceleration = 0.5
PayloadSpeedSettings.flat.most_hostiles = PayloadSpeedSettings.flat.most_hostiles or {}
PayloadSpeedSettings.flat.most_hostiles.speed = -0.25
PayloadSpeedSettings.flat.most_hostiles.acceleration = 0.5
PayloadSpeedSettings.flat.not_pushed = PayloadSpeedSettings.flat.not_pushed or {}
PayloadSpeedSettings.flat.not_pushed.speed = 0
PayloadSpeedSettings.flat.not_pushed.acceleration = 0.5
PayloadSpeedSettings.uphill = PayloadSpeedSettings.uphill or {}
PayloadSpeedSettings.uphill.most_friendlies = PayloadSpeedSettings.uphill.most_friendlies or {}
PayloadSpeedSettings.uphill.most_friendlies.speed = 0.8
PayloadSpeedSettings.uphill.most_friendlies.acceleration = 1.2
PayloadSpeedSettings.uphill.equal_amount = PayloadSpeedSettings.uphill.equal_amount or {}
PayloadSpeedSettings.uphill.equal_amount.speed = 0
PayloadSpeedSettings.uphill.equal_amount.acceleration = 0.3
PayloadSpeedSettings.uphill.most_hostiles = PayloadSpeedSettings.uphill.most_hostiles or {}
PayloadSpeedSettings.uphill.most_hostiles.speed = -1.25
PayloadSpeedSettings.uphill.most_hostiles.acceleration = 0.5
PayloadSpeedSettings.uphill.not_pushed = PayloadSpeedSettings.uphill.not_pushed or {}
PayloadSpeedSettings.uphill.not_pushed.speed = -1
PayloadSpeedSettings.uphill.not_pushed.acceleration = 0.3
PayloadSpeedSettings.downhill = PayloadSpeedSettings.downhill or {}
PayloadSpeedSettings.downhill.most_friendlies = PayloadSpeedSettings.downhill.most_friendlies or {}
PayloadSpeedSettings.downhill.most_friendlies.speed = 2
PayloadSpeedSettings.downhill.most_friendlies.acceleration = 0.5
PayloadSpeedSettings.downhill.equal_amount = PayloadSpeedSettings.downhill.equal_amount or {}
PayloadSpeedSettings.downhill.equal_amount.speed = 0
PayloadSpeedSettings.downhill.equal_amount.acceleration = 0.5
PayloadSpeedSettings.downhill.most_hostiles = PayloadSpeedSettings.downhill.most_hostiles or {}
PayloadSpeedSettings.downhill.most_hostiles.speed = -0.75
PayloadSpeedSettings.downhill.most_hostiles.acceleration = 0.5
PayloadSpeedSettings.downhill.not_pushed = PayloadSpeedSettings.downhill.not_pushed or {}
PayloadSpeedSettings.downhill.not_pushed.speed = 1
PayloadSpeedSettings.downhill.not_pushed.acceleration = 0.5
PayloadSpeedSettings.muddy = PayloadSpeedSettings.muddy or {}
PayloadSpeedSettings.muddy.most_friendlies = PayloadSpeedSettings.muddy.most_friendlies or {}
PayloadSpeedSettings.muddy.most_friendlies.speed = 0.8
PayloadSpeedSettings.muddy.most_friendlies.acceleration = 0.5
PayloadSpeedSettings.muddy.equal_amount = PayloadSpeedSettings.muddy.equal_amount or {}
PayloadSpeedSettings.muddy.equal_amount.speed = 0
PayloadSpeedSettings.muddy.equal_amount.acceleration = 0.5
PayloadSpeedSettings.muddy.most_hostiles = PayloadSpeedSettings.muddy.most_hostiles or {}
PayloadSpeedSettings.muddy.most_hostiles.speed = -0.25
PayloadSpeedSettings.muddy.most_hostiles.acceleration = 0.5
PayloadSpeedSettings.muddy.not_pushed = PayloadSpeedSettings.muddy.not_pushed or {}
PayloadSpeedSettings.muddy.not_pushed.speed = 0
PayloadSpeedSettings.muddy.not_pushed.acceleration = 0.5
